epochs: 400
classWeight: 0.6
updateClip: 0.005
class_num: 60
model_name: 'stgcn'
data_path: '/23085412008/HelloSkeleton/data/NTU-RGB-D-60-AGCN/xsub/train_data_joint.npy'
label_path: '/23085412008/HelloSkeleton/data/NTU-RGB-D-60-AGCN/xsub/train_label.pkl'
num_frame_path: '/23085412008/HelloSkeleton/data/NTU-RGB-D-60-AGCN/xsub/train_num_frame.npy'
save_path: '/23085412008/SVAttack_Github/对抗样本/svattack/stgcn/ntu60-cs-gd/'
batch_size: 64
hookstatus: True
hookratio: 0.1
end_sample_num: 5000
clamp_delta: 0.01
